# Generated by Django 5.1.3 on 2024-11-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dikde3vj3/image/upload/v<version>/default_profile_f0fbij.jpg', upload_to='images/'),
        ),
    ]
