# Generated by Django 5.1.3 on 2024-12-04 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_post_image_filter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
