# Generated by Django 4.2 on 2024-12-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_f0fbij.jpg', upload_to='images/'),
        ),
    ]
